language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g typescript
install:
  - npm install
script:
  - npm run lint
  - npm run build
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "TravisCI"
  - git config --local user.email "samuraitruong@hotmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - rm .gitignore
deploy:
  - provider: npm
    email: "samuraitruong@hotmail.com"
    api_key: "$(NPMTOKEN)"
    on:
      tags: true
      branch: master
  
# notifications:
#   webhooks:
#     urls:
#       - "https://us-central1-build-status-light-bulb.cloudfunctions.net/http"
#     on_success: change # default: always
#     on_failure: always # default: always
#     on_start: change   # default: never
#     on_cancel: always # default: always
#     on_error: always # default: always